# Generated by Django 5.2.5 on 2026-02-04 09:18
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
